name: CICD

on:
  push:
    branches:
    - main:

permission:
  id-token: write
  contents: read

jobs:

  security::
    run-on: ubuntu-latest

    default:
      run:
        working-directory: ./20june26/environment/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4 
  
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint  

      - name: tfsec action
        uses: aquasecurity/tfsec-action@v1.0.3
      
    
  validate:
    need: security
    run-on: ubuntu-latest
    default:
      run:
        working-directory: ./20june26/environment/dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
  
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        uses: action/checkout@v.7.0
        run: terraform fmt
        run: terraform validate

  plan:
    need: validate
    run-on: ubuntu-latest
    default:
      run:
        working-directory: ./20june26/environment/dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4 
  
    - name: Azure login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    run: terraform init
    run: terraform plan
      
  apply:
    need: plan
    run-on: ubuntu-latest
    default:
      run:
        working-directory: ./20june26/environment/dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4 
  
    - name: Azure login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    run: terraform init
    run: terraform apply -auto-approve
