name: cicd porcess

on:
  push:
    branches:
      - main

jobs:
   Scuritycheck:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./20june26/environment/dev
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4 
  
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
       
      - name: tflint-action
        uses: chnsz/tflint-action@master

      - name: tfsec action
        uses: aquasecurity/tfsec-action@v1.0.3
   
   validate:      
      needs: Scuritycheck
      runs-on: ubuntu-latest   
      
      defaults:
        run:
          working-directory: ./20june26/environment/dev
    
      steps:
        
        - uses: actions/checkout@v4

        - uses: hashicorp/setup-terraform@v4
         
       
        - name: Terraform fmt
          run: terraform fmt -check
          continue-on-error: true

        - name: Terraform Init
          run: terraform init -input=false

        - name: Terraform Validate
          run: terraform validate -no-color

   plan:
      needs: validate
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: ./20june26/environment/dev
      
      steps:
      
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v4   

        - name: Terraform Init
          run: terraform init -input=false 
      
        - name: Terraform Plan
          run: terraform plan -no-color -input=false

   apply:
      needs: plan
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: ./20june26/environment/dev
      
      steps:
      
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v4    

        - name: Terraform Init
          run: terraform init -input=false 
      
        - name: Terraform Plan
          run: terraform plan -no-color -input=false    
          
        - name: Terraform apply 
          run: terraform apply -auto-approve
